### ISSUE TITLE
Generating Embeddings Doesn't Work.

### ISSUE THREAD

**Issue by BrandonFrenz** [kiharalab/Distance-AF#1]
Hey I am trying to generate the embeddings to test out distance AF however the code in the collab doesn't seem to run for me. It fails in step 4 with the error: SymbolAlreadyExposedError: Symbol Zeros is already exposed as ().

**Comment by Zhang038** [comment]
Hello, I am trying to fix it as the error occurs because of the change run time from colab. I will modify Colabfold's script which is runnable now as our base, then the new one will help you to generate embeddings. Once I finish and test it then I will update here. Sorry for the issue. 

Update: Hello everyone, I will try to test and complete the v2 colab file in these 2 days by Jan 11th. Due to the limited run times of google colab, I cannot complete it in 1 day, please check our repo at that time. Thank you for your interest in Distance-AF. If you have any other problem or question, I am happy to answer it.

**Comment by lucajovine** [comment]
Hi, also encountering the same exact issue!

**Comment by Zhang038** [comment]
Hi all, I have complete another colab script for you to generate embeddings. This version 2 script will apply MMseq not full MSA used in AF2, besides this, all others are the same as the previous script. It has passed test on my side but not sure if works for you. Please feel free to run our [Distance_AF_embedding_v2.ipynb](https://github.com/kiharalab/Distance-AF/blob/9a978f90e46fb9c2ea22f1822d704923de11bfcf/Distance_AF_embedding_v2.ipynb), and tell me if you have any problems.

**Comment by lucajovine** [comment]
Thanks, however now I get the following at Run Prediction:

AttributeError                            Traceback (most recent call last)
[<ipython-input-9-f75dded47315>](https://localhost:8080/#) in <cell line: 16>()
     14 from colabfold.download import download_alphafold_params, default_data_dir
     15 from colabfold.utils import setup_logging
---> 16 from colabfold.batch import get_queries, run, set_model_type
     17 from colabfold.plot import plot_msa_v2
     18 

4 frames
[/usr/local/lib/python3.10/dist-packages/jax/_src/lib/__init__.py](https://localhost:8080/#) in <module>
     73 version_str = jaxlib.version.__version__
     74 version = check_jaxlib_version(
---> 75   jax_version=jax.version.__version__,
     76   jaxlib_version=jaxlib.version.__version__,
     77   minimum_jaxlib_version=jax.version._minimum_jaxlib_version)

AttributeError: partially initialized module 'jax' has no attribute 'version' (most likely due to a circular import)

**Comment by lucajovine** [comment]
Also, not all required dependencies are installed:

lida 0.0.10 requires fastapi, which is not installed.
lida 0.0.10 requires kaleido, which is not installed.
lida 0.0.10 requires python-multipart, which is not installed.
lida 0.0.10 requires uvicorn, which is not installed.
google-colab 1.0.0 requires pandas==1.5.3, but you have pandas 2.0.3 which is incompatible.
optax 0.1.7 requires chex>=0.1.5, but you have chex 0.0.7 which is incompatible.
tensorflow 2.12.0 requires keras<2.13,>=2.12.0, but you have keras 2.13.1 which is incompatible.
tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.24.3 which is incompatible.
tensorflow 2.12.0 requires tensorboard<2.13,>=2.12, but you have tensorboard 2.13.0 which is incompatible.
tensorflow 2.12.0 requires tensorflow-estimator<2.13,>=2.12.0, but you have tensorflow-estimator 2.13.0 which is incompatible.

**Comment by lucajovine** [comment]
PS: the above is on TPU, if I choose a T4 GPU then I get:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-1-f75dded47315>](https://localhost:8080/#) in <cell line: 11>()
      9 import warnings
     10 warnings.simplefilter(action='ignore', category=FutureWarning)
---> 11 from Bio import BiopythonDeprecationWarning
     12 warnings.simplefilter(action='ignore', category=BiopythonDeprecationWarning)
     13 from pathlib import Path

ModuleNotFoundError: No module named 'Bio'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by lucajovine** [comment]
HI, after a few attempts I could finally get the colab to run on A100, but when the run was done I could download PDB files but not the associated embeddings (they were listed, but could never be downloaded). Moreover, at least in the case I tried the predictions were significantly less good than what I got from standalone AlphaFold (2.3.2). So my question is, is there any way to generate model 1-5.npz from the output of standalone AlphaFold?

**Comment by Zhang038** [comment]
> HI, after a few attempts I could finally get the colab to run on A100, but when the run was done I could download PDB files but not the associated embeddings (they were listed, but could never be downloaded). Moreover, at least in the case I tried the predictions were significantly less good than what I got from standalone AlphaFold (2.3.2). So my question is, is there any way to generate model 1-5.npz from the output of standalone AlphaFold?

Hello, sorry for the problem caused.
1. For your first question, the embeddings and pdbs are supposed to be downloaded into 1 zip file together, if it is not, please follow the steps below to download embedding file.

- 1. Go to the colab folder
![image](https://github.com/kiharalab/Distance-AF/assets/100041384/7bf0db3a-6dfe-44d4-83ea-0b6bc19e50af)
- 2. Go to the folder taking the job name as prefix
![image](https://github.com/kiharalab/Distance-AF/assets/100041384/555b54eb-99c2-424e-aa48-2ef1184e2e37)
- 3. Put your pointer on the embedding file with 'npz' and click the right side.
![image](https://github.com/kiharalab/Distance-AF/assets/100041384/0821797d-0f3e-43e0-ad28-d4fceaef0239)
- 4. Choose Download then you can have this single embedding on your local machine
![image](https://github.com/kiharalab/Distance-AF/assets/100041384/5579bc16-74fd-473c-8947-3ef4d3933343)

For more friendly usage, I add one option 'save_to_google_drive', if you enable it, the result zip file will be saved automatically to your google drive.

2. For the second question, as the new colab script using MMseq MSA, it will not search the whole database as standard AlphaFold2, it might be the reason that the produced structures are different or worse than standard AlphaFold2, the [Distance_AF_embedding.ipynb](https://github.com/kiharalab/Distance-AF/blob/main/Distance_AF_embedding.ipynb) is developed exactly same as AlphaFold2 but as it contains error now. The error is caused by original AlphaFold getting affected by recent changes of colab ([reference here](https://github.com/google-deepmind/alphafold/issues/875)), I am still waiting for AlphaFold2 group to fix it.

**Comment by lucajovine** [comment]
Hi, thanks for the reply. I tried exactly what you described, but after right clicking nothing happened for either the individual *.npz files or the whole archive... they just never got downloaded. Same procedure for PDB files worked though!

**Comment by Zhang038** [comment]
Could you please share me with your folder view? I just reran it, if the output box shows 'Running model X successfully!', the corresponding 'model_X.npz' and 'model_X.pdb' should exist.
![image](https://github.com/kiharalab/Distance-AF/assets/100041384/fdc2b265-79b1-4354-b756-b918666ce966)

**Comment by lucajovine** [comment]
I'm afraid that I deleted it, but I can run it again. In any case, yes I saw exactly the same as you are showing.
